# Generated by Django 4.2.7 on 2023-11-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_age', models.IntegerField()),
                ('client_city', models.CharField(max_length=100)),
                ('client_food', models.CharField(max_length=20, null=True)),
                ('client_phone', models.CharField(max_length=200, null=True)),
                ('client_image', models.CharField(max_length=200, null=True)),
                ('client_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_money', models.IntegerField()),
                ('client_id', models.IntegerField(null=True)),
            ],
        ),
    ]
